server:
  port: 6001

#\u670D\u52A1\u7684\u540D\u79F0
spring:
  application:
    name: zuul-gateway

#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.13.128:8081/eurekaserver/eureka/

#\u81EA\u5B9A\u4E49\u8DEF\u7531\u6620\u5C04
zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
  #\u7EDF\u4E00\u5165\u53E3\u4E3A\u4E0A\u9762\u7684\u914D\u7F6E\uFF0C\u5176\u4ED6\u5165\u53E3\u5FFD\u7565
  ignored-patterns: /*-service/**
  #\u5FFD\u7565\u6574\u4E2A\u670D\u52A1\uFF0C\u5BF9\u5916\u63D0\u4F9B\u63A5\u53E3
  ignored-services: order-service
